	
	UPDATE DATOS\mxart SET COMANDA1 = "", COMANDA2 = "" WHERE EMPTY(TEXTO1)
 	UPDATE DATOS\mxart SET COMANDA1 = "U", COMANDA2 = "" WHERE TEXTO1 = "0"
 	UPDATE DATOS\mxart SET COMANDA1 = "U", COMANDA2 = "1" WHERE TEXTO1 = "1"
 	
 
 	 		
	WAIT WINDOW "Comandas actualizadas correctamente!" TIMEOUT 3
